name: pop_tarts
description: Pop-Tarts box, scanned mesh with texture
category: [food_package, graspable]

# Physical properties
mass: 0.35  # kg (full box)
dimensions: [0.093, 0.097, 0.141]  # [width, depth, height] in meters
material: cardboard

# Geometric properties for grasp planning
geometric_properties:
  type: box
  size: [0.093, 0.097, 0.141]  # full extents

# MuJoCo simulation
mujoco:
  xml_path: pop_tarts.xml
  scale: 1.0
  friction: [0.7, 0.005, 0.0001]

# Perception aliases for detection systems
perception:
  aliases: ["pop tarts", "poptarts", "cereal box", "food box"]

# Manipulation policy hints
policy:
  grasping:
    affordances: [lift, place]
    preferred_grasp_type: side_grasp
    graspable_height_range: [0.02, 0.12]
    difficulty: easy
  manipulation:
    stable_poses: [upright, on_side, on_back]
