name: can
description: Standard aluminum soda/beer can for manipulation tasks
category: [container, recyclable, graspable]

# Physical properties
mass: 0.05  # kg (partially full)
dimensions: [0.066, 0.066, 0.123]  # [diameter, diameter, height] in meters
color: [0.8, 0.1, 0.1]  # RGB (red)
material: aluminum

# Geometric properties for grasp planning
geometric_properties:
  type: cylinder
  radius: 0.033  # meters
  height: 0.123  # meters

# MuJoCo simulation
mujoco:
  xml_path: can.xml
  scale: 1.0
  friction: [0.6, 0.005, 0.0001]

# Perception aliases for detection systems
perception:
  aliases: ["can", "soda can", "beer can", "aluminum can", "drink can"]

# Manipulation policy hints
policy:
  grasping:
    affordances: [lift, pour]
    preferred_grasp_type: side_grasp
    graspable_height_range: [0.02, 0.10]  # meters - avoid top lip and bottom edge
    difficulty: easy
  manipulation:
    stable_poses: [upright, on_side]
