name: yellow_tote
description: Yellow storage tote container
category: [container, receptacle]

mass: 0.7  # kg
dimensions: [0.6, 0.38, 0.29]  # meters
material: plastic

geometric_properties:
  type: tote
  outer_size: [0.6, 0.38, 0.29]
  wall_thickness: 0.02
  floor_thickness: 0.01

mujoco:
  xml_path: yellow_tote.xml
  scale: 1.0
  friction: [0.7, 0.005, 0.0001]

perception:
  aliases: ["tote", "yellow tote", "storage bin", "storage tote"]

policy:
  grasping:
    affordances: [lift, carry, place]
    preferred_grasp_type: side_grasp
    difficulty: medium
  manipulation:
    stable_poses: [upright]
    can_contain_objects: true
