name: fuze_bottle
description: Fuze beverage bottle, scanned mesh with texture
category: [container, graspable, beverage]

# Physical properties
mass: 0.4  # kg (full bottle ~500ml)
dimensions: [0.073, 0.073, 0.215]  # [width, depth, height] in meters
material: plastic

# Geometric properties for grasp planning
geometric_properties:
  type: cylinder
  radius: 0.037  # meters
  height: 0.215  # meters

# MuJoCo simulation
mujoco:
  xml_path: fuze_bottle.xml
  scale: 1.0
  friction: [0.8, 0.005, 0.0001]

# Perception aliases for detection systems
perception:
  aliases: ["fuze bottle", "beverage bottle", "drink bottle", "fuze"]

# Manipulation policy hints
policy:
  grasping:
    affordances: [lift, pour]
    preferred_grasp_type: side_grasp
    graspable_height_range: [0.05, 0.18]  # meters - main body
    difficulty: easy
  manipulation:
    stable_poses: [upright]
