name: sugar_box
description: Domino granulated sugar box
category: [food_package, graspable, box]

mass: 0.5  # kg
dimensions: [0.176, 0.094, 0.048]  # meters [X, Y, Z] in flat resting pose
material: cardboard
amazon_link: https://www.amazon.com/dp/B00O60NVHY

geometric_properties:
  type: box
  size: [0.176, 0.094, 0.048]

mujoco:
  xml_path: sugar_box.xml
  scale: 1.0
  friction: [0.7, 0.005, 0.0001]

perception:
  aliases: ["sugar box", "domino sugar", "sugar"]

policy:
  grasping:
    affordances: [lift, place]
    preferred_grasp_type: side_grasp
    difficulty: easy
  manipulation:
    stable_poses: [upright, on_side, on_back]
